---
- hosts: all
  tasks:
    - name: 'Set timezone to America/Los_Angeles'
      timezone:
        name: America/Los_Angeles

    - name: 'Update system packages'
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: 'Install commonly installed packages'
      apt:
        pkg:
          - curl
          - tmux
          - vim
          - zsh
        state: present

- hosts: all
  tags:
    - python
  tasks:
    - name: 'Install Python packages'
      apt:
        pkg:
          - build-essential
          - python3
          - python3-dev
          - python3-venv
        state: present
